name: 更新day.txt

on:
  schedule:
    - cron: '45 15 * * *'
  repository_dispatch:
    types: test
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 更新为中国时间
        run: |
          sudo rm -rf /etc/localtime 
          sudo ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          date
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
      - name: "更新day.txt"
        run: |
          bash ./main/test.sh
      - name: commit
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name xsk666
          git add .
          git commit -m "今日 by xsk666 Github Actions" -a || echo "day update"
      - name: 推送day.txt
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: master
