name: test

on:
  schedule:
  - cron: '30 * * * *'


jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: 安装requests
      run: |
        pip install requests
    - name: info test
      run: |
        python test.py
