name: 青年大学习每日登陆

on:
  workflow_dispatch:
  schedule:
    - cron: '59 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 更新为中国时间
        run: |
          sudo rm -rf /etc/localtime
          sudo ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          date

      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: 安装requests
        run: |
          python -m pip install requests
      - name: 运行脚本
        run: |
          python3 ./test/paolu/study.py
