name: 定时消息和邮件

on:
  schedule:
  - cron: '1 * * * *'
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: 安装requests
      run: |
        python -m pip install requests
    - name: 运行test.py和mail.py
      run: |
        python3 mail.py
