name: test2

on:
  schedule:
  - cron: '0,15,30,36,45 * * * *'
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 更新为中国时间
      run: |
        sudo rm -rf /etc/localtime 
        sudo ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        date
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 安装requests
      run: |
        python -m pip install requests
    - name: 运行test.py和email.py
      run: |
        python3 test.py
        python3 email.py
