name: 每日打卡

on:
  workflow_dispatch:
  schedule:
    - cron: '55 15,16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 更新为中国时间
        run: |
          sudo rm -rf /etc/localtime 
          sudo ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          date

      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: 安装requests
        run: |
          python -m pip install requests
      - name: 运行自动打卡脚本
        run: |
          python3 ./main/index.py
          python3 ./test/paolu/paolu.py
      - name: 推送文件
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name xsk666
          git add .
          git commit -m  date +%Y-%m-%d -a || echo "day update"
      - name: 推送day.txt
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}